# for local testing of bot (docker compose up)

version: '3.9'

services:
  intern_bot:
    build: .
    container_name: local_intern_bot_app
    ports:
      - "3001:3001"  # Host:Container
    env_file:
      - .env
    restart: unless-stopped
